// Temporary refactor script. Safe to delete after running.
const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, '..', 'backend', 'services', 'deepseekService.js');
let t = fs.readFileSync(file, 'utf8');
const CRLF = '\r\n';

function joinCRLF(arr) { return arr.join(CRLF); }

// === Block 1: API config ===
const oldBlock1 = joinCRLF([
  "// DeepSeek API configuration (via OpenRouter)",
  "const DEEPSEEK_API_URL = 'https://openrouter.ai/api/v1/chat/completions';",
  "const DEEPSEEK_API_KEY = process.env.DEEPSEEK_API_KEY;",
  "const DEEPSEEK_MODEL = process.env.DEEPSEEK_MODEL || 'deepseek/deepseek-chat-v3.1:free';",
  "",
  "if (!DEEPSEEK_API_KEY) {",
  "  console.warn('[DeepSeek] DEEPSEEK_API_KEY is not set. AI insights will fall back to deterministic responses.');",
  "}"
]);

const newBlock1 = joinCRLF([
  "// OpenRouter API configuration",
  "const DEEPSEEK_API_URL = 'https://openrouter.ai/api/v1/chat/completions';",
  "const DEEPSEEK_API_KEY = process.env.DEEPSEEK_API_KEY;",
  "",
  "// Default free-model fallback chain (tried in order)",
  "const DEFAULT_MODEL_CHAIN = [",
  "  'deepseek/deepseek-chat-v3.1:free',",
  "  'openai/gpt-oss-120b:free',",
  "  'google/gemma-4-31b:free',",
  "  'openrouter/free',",
  "];",
  "",
  "/**",
  " * Build the model chain from env vars:",
  " *  - DEEPSEEK_MODELS (CSV) takes full precedence over the default chain",
  " *  - DEEPSEEK_MODEL (single) is prepended to the default chain (deduplicated)",
  " */",
  "function buildModelChain() {",
  "  const csv = process.env.DEEPSEEK_MODELS;",
  "  if (csv && csv.trim()) {",
  "    const list = csv.split(',').map(s => s.trim()).filter(Boolean);",
  "    if (list.length > 0) return Array.from(new Set(list));",
  "  }",
  "  const single = process.env.DEEPSEEK_MODEL && process.env.DEEPSEEK_MODEL.trim();",
  "  if (single) {",
  "    return Array.from(new Set([single, ...DEFAULT_MODEL_CHAIN]));",
  "  }",
  "  return [...DEFAULT_MODEL_CHAIN];",
  "}",
  "",
  "const MODEL_CHAIN = buildModelChain();",
  "",
  "if (!DEEPSEEK_API_KEY) {",
  "  console.warn('[DeepSeek] DEEPSEEK_API_KEY is not set. AI insights will fall back to deterministic responses.');",
  "} else {",
  "  console.log(`[DeepSeek] Model fallback chain (${MODEL_CHAIN.length}): ${MODEL_CHAIN.join(' -> ')}`);",
  "}"
]);

if (!t.includes(oldBlock1)) { console.error('block1 NOT FOUND'); process.exit(1); }
t = t.replace(oldBlock1, newBlock1);
console.log('block1 OK');

// === Block 2: Replace isRetryableError + add helpers ===
const oldBlock2 = joinCRLF([
  "/**",
  " * Determine if an error is retryable (network/timeout errors)",
  " */",
  "function isRetryableError(error) {",
  "  const retryCodes = ['ECONNRESET', 'ECONNABORTED', 'ETIMEDOUT', 'ENOTFOUND', 'ECONNREFUSED'];",
  "  if (error.code && retryCodes.includes(error.code)) return true;",
  "  if (error.message) {",
  "    const msg = error.message.toLowerCase();",
  "    if (msg.includes('socket hang up') || msg.includes('econnreset') || msg.includes('timeout') || msg.includes('econnrefused')) return true;",
  "  }",
  "  // Don't retry on HTTP 4xx errors",
  "  if (error.response && error.response.status >= 400 && error.response.status < 500) return false;",
  "  return false;",
  "}"
]);

const newBlock2 = joinCRLF([
  "/**",
  " * Determine if an error is retryable on the SAME model (transient network errors only).",
  " */",
  "function isRetryableError(error) {",
  "  const retryCodes = ['ECONNRESET', 'ECONNABORTED', 'ETIMEDOUT', 'ENOTFOUND', 'ECONNREFUSED', 'EAI_AGAIN'];",
  "  if (error.code && retryCodes.includes(error.code)) return true;",
  "  if (error.message) {",
  "    const msg = error.message.toLowerCase();",
  "    if (",
  "      msg.includes('socket hang up') ||",
  "      msg.includes('econnreset') ||",
  "      msg.includes('timeout') ||",
  "      msg.includes('econnrefused') ||",
  "      msg.includes('network error')",
  "    ) return true;",
  "  }",
  "  // Never retry same model on HTTP responses (those are handled by shouldSwitchModel/isFatalError)",
  "  if (error.response) return false;",
  "  return false;",
  "}",
  "",
  "/**",
  " * Fatal errors abort the entire chain - no further models will be tried.",
  " * 400 (bad request), 401 (unauthorized), 403 (forbidden) indicate a problem",
  " * that won't be solved by switching models.",
  " */",
  "function isFatalError(error) {",
  "  if (!error || !error.response) return false;",
  "  const status = error.response.status;",
  "  return status === 400 || status === 401 || status === 403;",
  "}",
  "",
  "/**",
  " * Should we switch to the NEXT model in the chain?",
  " * Switch on: 402 (payment required), 404 (model not found),",
  " * 429 (rate limit), or any 5xx (server error).",
  " */",
  "function shouldSwitchModel(error) {",
  "  if (!error || !error.response) return false;",
  "  const status = error.response.status;",
  "  if (status === 402 || status === 404 || status === 429) return true;",
  "  if (status >= 500 && status < 600) return true;",
  "  return false;",
  "}",
  "",
  "/**",
  " * Call OpenRouter for a specific model with up to 2 attempts.",
  " * Retries the SAME model only on transient network errors.",
  " * Throws the last error otherwise (caller decides whether to switch model).",
  " */",
  "async function callOpenRouter(model, messages, opts = {}) {",
  "  const {",
  "    maxAttempts = 2,",
  "    timeoutMs = 15000,",
  "    maxTokens = 2000,",
  "    temperature = 0.7,",
  "  } = opts;",
  "",
  "  let lastError = null;",
  "",
  "  for (let attempt = 1; attempt <= maxAttempts; attempt++) {",
  "    const controller = new AbortController();",
  "    const abortTimer = setTimeout(() => controller.abort(), Math.max(1000, timeoutMs - 1000));",
  "",
  "    try {",
  "      console.log(`[DeepSeek] -> Calling model \"${model}\" (attempt ${attempt}/${maxAttempts})`);",
  "      const response = await axios.post(",
  "        DEEPSEEK_API_URL,",
  "        {",
  "          model,",
  "          messages,",
  "          max_tokens: maxTokens,",
  "          temperature,",
  "        },",
  "        {",
  "          headers: {",
  "            'Authorization': `Bearer ${DEEPSEEK_API_KEY}`,",
  "            'Content-Type': 'application/json',",
  "            'HTTP-Referer': 'https://church-planting-map.app',",
  "            'X-Title': 'Church Planting Map - DMM Analysis',",
  "          },",
  "          timeout: timeoutMs,",
  "          signal: controller.signal,",
  "        }",
  "      );",
  "      clearTimeout(abortTimer);",
  "      return response;",
  "    } catch (error) {",
  "      clearTimeout(abortTimer);",
  "      lastError = error;",
  "      const status = error.response && error.response.status;",
  "      console.error(",
  "        `[DeepSeek]    Model \"${model}\" attempt ${attempt}/${maxAttempts} failed. ` +",
  "        `Status: ${status || 'N/A'}, Code: ${error.code || 'N/A'}, Message: ${error.message}`",
  "      );",
  "",
  "      // If it's a transient network error and we have attempts left, retry same model.",
  "      if (attempt < maxAttempts && isRetryableError(error)) {",
  "        console.log(`[DeepSeek]    Transient error - retrying same model in 1s...`);",
  "        await sleep(1000);",
  "        continue;",
  "      }",
  "      // Otherwise stop attempting this model.",
  "      throw error;",
  "    }",
  "  }",
  "",
  "  // Defensive - should not reach here.",
  "  throw lastError || new Error('callOpenRouter exhausted attempts without an error');",
  "}"
]);

if (!t.includes(oldBlock2)) { console.error('block2 NOT FOUND'); process.exit(1); }
t = t.replace(oldBlock2, newBlock2);
console.log('block2 OK');

// === Block 3: Replace inline retry loop in generateAnalysisInsights ===
const oldBlock3 = joinCRLF([
  "  const MAX_ATTEMPTS = 3;",
  "  const REQUEST_TIMEOUT_MS = 15000;",
  "  let lastError = null;",
  "",
  "  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {",
  "    const controller = new AbortController();",
  "    const abortTimer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS - 1000);",
  "",
  "    try {",
  "      console.log(`[DeepSeek] Attempt ${attempt}/${MAX_ATTEMPTS} for insights generation...`);",
  "      if (!DEEPSEEK_API_KEY) {",
  "        throw new Error('DEEPSEEK_API_KEY environment variable is not configured');",
  "      }",
  "      const response = await axios.post(",
  "        DEEPSEEK_API_URL,",
  "        {",
  "          model: DEEPSEEK_MODEL,",
  "          messages: [",
  "            {",
  "              role: 'system',",
  "              content: 'You are an expert consultant in Disciple Making Movements (DMM) and church planting. You provide insightful analysis and practical recommendations based on DMM DNA criteria assessments. Always respond in French.',",
  "            },",
  "            {",
  "              role: 'user',",
  "              content: prompt,",
  "            },",
  "          ],",
  "          max_tokens: 2000,",
  "          temperature: 0.7,",
  "        },",
  "        {",
  "          headers: {",
  "            'Authorization': `Bearer ${DEEPSEEK_API_KEY}`,",
  "            'Content-Type': 'application/json',",
  "            'HTTP-Referer': 'https://church-planting-map.app',",
  "            'X-Title': 'Church Planting Map - DMM Analysis',",
  "          },",
  "          timeout: REQUEST_TIMEOUT_MS,",
  "          signal: controller.signal,",
  "        }",
  "      );",
  "",
  "      clearTimeout(abortTimer);",
  "      const aiResponse = response.data.choices[0]?.message?.content || '';",
  "      const { interpretation, recommendations } = parseAIResponse(aiResponse);",
  "",
  "      return {",
  "        success: true,",
  "        interpretation,",
  "        recommendations,",
  "        rawResponse: aiResponse,",
  "      };",
  "    } catch (error) {",
  "      clearTimeout(abortTimer);",
  "      lastError = error;",
  "      console.error(`[DeepSeek] Attempt ${attempt}/${MAX_ATTEMPTS} failed. Code: ${error.code || 'N/A'}, Message: ${error.message}`);",
  "",
  "      if (attempt < MAX_ATTEMPTS && isRetryableError(error)) {",
  "        console.log(`[DeepSeek] Retrying in 1s...`);",
  "        await sleep(1000);",
  "      } else {",
  "        break;",
  "      }",
  "    }",
  "  }",
  "",
  "  console.error(`[DeepSeek] All ${MAX_ATTEMPTS} attempts failed. Last error: ${lastError?.message}`);",
  "  return {",
  "    success: false,",
  "    error: lastError?.message,",
  "    interpretation: generateFallbackInterpretation(analysisData),",
  "    recommendations: generateFallbackRecommendations(analysisData),",
  "  };",
  "}"
]);

const newBlock3 = joinCRLF([
  "  // Short-circuit if no API key - return deterministic fallback immediately.",
  "  if (!DEEPSEEK_API_KEY) {",
  "    console.warn('[DeepSeek] No DEEPSEEK_API_KEY configured - returning deterministic fallback.');",
  "    return {",
  "      success: false,",
  "      error: 'DEEPSEEK_API_KEY environment variable is not configured',",
  "      triedModels: [],",
  "      interpretation: generateFallbackInterpretation(analysisData),",
  "      recommendations: generateFallbackRecommendations(analysisData),",
  "    };",
  "  }",
  "",
  "  const messages = [",
  "    {",
  "      role: 'system',",
  "      content: 'You are an expert consultant in Disciple Making Movements (DMM) and church planting. You provide insightful analysis and practical recommendations based on DMM DNA criteria assessments. Always respond in French.',",
  "    },",
  "    {",
  "      role: 'user',",
  "      content: prompt,",
  "    },",
  "  ];",
  "",
  "  const triedModels = [];",
  "  let lastError = null;",
  "",
  "  console.log(`[DeepSeek] Starting insights generation across ${MODEL_CHAIN.length} model(s).`);",
  "",
  "  for (let i = 0; i < MODEL_CHAIN.length; i++) {",
  "    const model = MODEL_CHAIN[i];",
  "    triedModels.push(model);",
  "",
  "    try {",
  "      const response = await callOpenRouter(model, messages, {",
  "        maxAttempts: 2,",
  "        timeoutMs: 15000,",
  "        maxTokens: 2000,",
  "        temperature: 0.7,",
  "      });",
  "",
  "      const aiResponse = response.data.choices[0]?.message?.content || '';",
  "      const { interpretation, recommendations } = parseAIResponse(aiResponse);",
  "",
  "      console.log(`[DeepSeek] OK Success with model \"${model}\" (after trying ${triedModels.length}/${MODEL_CHAIN.length}).`);",
  "",
  "      return {",
  "        success: true,",
  "        modelUsed: model,",
  "        interpretation,",
  "        recommendations,",
  "        rawResponse: aiResponse,",
  "      };",
  "    } catch (error) {",
  "      lastError = error;",
  "      const status = error.response && error.response.status;",
  "",
  "      if (isFatalError(error)) {",
  "        console.error(`[DeepSeek] FATAL error (status ${status}) on model \"${model}\" - aborting entire chain.`);",
  "        break;",
  "      }",
  "",
  "      if (shouldSwitchModel(error)) {",
  "        const reason = status ? `HTTP ${status}` : (error.code || 'unknown');",
  "        const next = MODEL_CHAIN[i + 1];",
  "        if (next) {",
  "          console.warn(`[DeepSeek] Switching model: \"${model}\" failed with ${reason} - trying next model \"${next}\".`);",
  "        } else {",
  "          console.warn(`[DeepSeek] Model \"${model}\" failed with ${reason} - no more models in chain.`);",
  "        }",
  "        continue;",
  "      }",
  "",
  "      // Non-switchable, non-fatal error (e.g. exhausted network retries on this model).",
  "      // Try the next model anyway as a best effort.",
  "      const next = MODEL_CHAIN[i + 1];",
  "      if (next) {",
  "        console.warn(`[DeepSeek] Non-switch error on \"${model}\" (${error.code || error.message}) - falling through to next model \"${next}\".`);",
  "      } else {",
  "        console.warn(`[DeepSeek] Non-switch error on \"${model}\" (${error.code || error.message}) - no more models in chain.`);",
  "      }",
  "      continue;",
  "    }",
  "  }",
  "",
  "  console.error(",
  "    `[DeepSeek] All models exhausted. Tried: [${triedModels.join(', ')}]. ` +",
  "    `Last error: ${lastError ? lastError.message : 'unknown'}`",
  "  );",
  "  return {",
  "    success: false,",
  "    error: lastError ? lastError.message : 'All models failed',",
  "    triedModels,",
  "    interpretation: generateFallbackInterpretation(analysisData),",
  "    recommendations: generateFallbackRecommendations(analysisData),",
  "  };",
  "}"
]);

if (!t.includes(oldBlock3)) { console.error('block3 NOT FOUND'); process.exit(1); }
t = t.replace(oldBlock3, newBlock3);
console.log('block3 OK');

fs.writeFileSync(file, t);
console.log('FILE WRITTEN:', file);
console.log('FINAL SIZE:', t.length);
console.log('CRLF preserved:', t.includes('\r\n'));
console.log('LF-only lines:', (t.match(/(?<!\r)\n/g) || []).length);
